import JSZip from 'jszip'
import { compileTheme, minifyCss } from '../compiler'
import { kitchenSink } from '../preview/specimens'
import type { Theme } from '../theme/schema'

function safeName(name: string): string {
  return name.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'semantic-theme'
}

export function themeJson(theme: Theme): string {
  return `${JSON.stringify(theme, null, 2)}\n`
}

export function demoHtml(theme: Theme): string {
  const title = theme.metadata.name.replace(/[&<>"']/g, '')
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title} — Semantic CSS demo</title>
  <link rel="stylesheet" href="theme.css">
</head>
<body>
${kitchenSink}
</body>
</html>
`
}

export function downloadText(filename: string, content: string, type = 'text/plain;charset=utf-8'): void {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  URL.revokeObjectURL(url)
}

export function exportCss(theme: Theme): void {
  downloadText(`${safeName(theme.metadata.name)}.css`, compileTheme(theme), 'text/css;charset=utf-8')
}

export function exportMinCss(theme: Theme): void {
  downloadText(`${safeName(theme.metadata.name)}.min.css`, minifyCss(compileTheme(theme)), 'text/css;charset=utf-8')
}

export function exportJson(theme: Theme): void {
  downloadText(`${safeName(theme.metadata.name)}.json`, themeJson(theme), 'application/json;charset=utf-8')
}

export function exportDemo(theme: Theme): void {
  downloadText('demo.html', demoHtml(theme), 'text/html;charset=utf-8')
}

export async function exportPackage(theme: Theme): Promise<void> {
  const zip = new JSZip()
  const folder = zip.folder(safeName(theme.metadata.name))
  if (!folder) throw new Error('Could not create export package.')
  const css = compileTheme(theme)
  folder.file('theme.css', css)
  folder.file('theme.min.css', minifyCss(css))
  folder.file('theme.json', themeJson(theme))
  folder.file('demo.html', demoHtml(theme))
  folder.file('README.txt', `${theme.metadata.name}\n\nOpen demo.html or link theme.css from any semantic HTML document.\nGenerated by Semantic CSS Studio.\n`)
  const blob = await zip.generateAsync({ type: 'blob' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `${safeName(theme.metadata.name)}.zip`
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  URL.revokeObjectURL(url)
}
