import JSZip from 'jszip'
import { compileTheme, minifyCss } from '../compiler'
import { kitchenSink } from '../preview/specimens'
import type { Theme } from '../theme/schema'
import { quartoCss, type QuartoColorMode } from './quarto'

function safeName(name: string): string {
  return (
    name
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') || 'semantic-theme'
  )
}

export function themeJson(theme: Theme): string {
  return `${JSON.stringify(theme, null, 2)}\n`
}

export type DemoColorMode = QuartoColorMode

export function demoHtml(
  theme: Theme,
  mode: DemoColorMode = 'auto',
  stylesheet = 'theme.css',
): string {
  const title = theme.metadata.name.replace(/[&<>"']/g, '')
  // Exported CSS applies dark via `@media (prefers-color-scheme: dark)` when
  // there is no `data-theme`. Without pinning the mode here, an exported demo
  // with the preview in "light" opens dark on an OS with a dark theme — the
  // reported bug.
  const htmlTag =
    mode === 'auto'
      ? '<html lang="en">'
      : `<html lang="en" data-theme="${mode}">`
  return `<!doctype html>
${htmlTag}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title} — Semantic CSS demo</title>
  <link rel="stylesheet" href="${stylesheet.replace(/[&<>"']/g, '')}">
</head>
<body>
${kitchenSink}
</body>
</html>
`
}

export function downloadText(
  filename: string,
  content: string,
  type = 'text/plain;charset=utf-8',
): void {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  URL.revokeObjectURL(url)
}

export function exportCss(theme: Theme): void {
  downloadText(
    `${safeName(theme.metadata.name)}.css`,
    compileTheme(theme),
    'text/css;charset=utf-8',
  )
}

export function exportQuarto(
  theme: Theme,
  mode: DemoColorMode = 'auto',
  filename = 'theme.css',
): void {
  downloadText(filename, quartoCss(theme, mode), 'text/css;charset=utf-8')
}

export function exportMinCss(theme: Theme): void {
  downloadText(
    `${safeName(theme.metadata.name)}.min.css`,
    minifyCss(compileTheme(theme)),
    'text/css;charset=utf-8',
  )
}

export function exportJson(theme: Theme): void {
  downloadText(
    `${safeName(theme.metadata.name)}.json`,
    themeJson(theme),
    'application/json;charset=utf-8',
  )
}

export function exportDemo(theme: Theme, mode: DemoColorMode = 'auto'): void {
  downloadText(
    'demo.html',
    demoHtml(theme, mode, `${safeName(theme.metadata.name)}.css`),
    'text/html;charset=utf-8',
  )
}

export async function exportPackage(
  theme: Theme,
  mode: DemoColorMode = 'auto',
): Promise<void> {
  const zip = new JSZip()
  const folder = zip.folder(safeName(theme.metadata.name))
  if (!folder) throw new Error('Could not create export package.')
  const css = compileTheme(theme)
  folder.file('theme.css', css)
  folder.file('theme.min.css', minifyCss(css))
  folder.file('theme.json', themeJson(theme))
  folder.file('demo.html', demoHtml(theme, mode))
  folder.file(
    'README.txt',
    `${theme.metadata.name}\n\nOpen demo.html or link theme.css from any semantic HTML document.\nGenerated by Semantic CSS Studio.\n`,
  )
  const blob = await zip.generateAsync({ type: 'blob' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `${safeName(theme.metadata.name)}.zip`
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  URL.revokeObjectURL(url)
}
