project:
  type: website
website:
  title: Field notes
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Journal
      - href: '#methods'
        text: Methods
  page-footer: A reference document for Semantic CSS Studio
format:
  html:
    theme: cosmo
    toc: true
    toc-title: On this page
    number-sections: true
    embed-resources: true
    anchor-sections: false
    code-copy: false
    smooth-scroll: false
    citations-hover: false
    footnotes-hover: false
    lang: en
