import { defaultTheme } from '../defaults'
import type { Theme } from '../schema'

function preset(overrides: Partial<Theme> & { metadata: Theme['metadata'] }): Theme {
  const base = structuredClone(defaultTheme)
  return {
    ...base,
    ...overrides,
    metadata: overrides.metadata,
    tokens: {
      ...base.tokens,
      ...(overrides.tokens ?? {}),
      colors: { ...base.tokens.colors, ...(overrides.tokens?.colors ?? {}) },
      typography: { ...base.tokens.typography, ...(overrides.tokens?.typography ?? {}) },
      spacing: { ...base.tokens.spacing, ...(overrides.tokens?.spacing ?? {}) },
      radius: { ...base.tokens.radius, ...(overrides.tokens?.radius ?? {}) },
      shadow: { ...base.tokens.shadow, ...(overrides.tokens?.shadow ?? {}) },
      layout: { ...base.tokens.layout, ...(overrides.tokens?.layout ?? {}) },
    },
    modes: {
      light: { colors: { ...base.modes.light.colors, ...(overrides.modes?.light.colors ?? {}) } },
      dark: overrides.modes?.dark
        ? { colors: { ...base.modes.dark?.colors, ...overrides.modes.dark.colors } }
        : base.modes.dark,
    },
    elements: { ...base.elements, ...(overrides.elements ?? {}) },
    states: { ...base.states, ...(overrides.states ?? {}) },
    responsive: { ...base.responsive, ...(overrides.responsive ?? {}) },
    options: { ...base.options, ...(overrides.options ?? {}) },
  }
}

export const minimalPreset = structuredClone(defaultTheme)

export const editorialPreset = preset({
  metadata: {
    name: 'Editorial',
    description: 'A serif-forward theme for essays, magazines and long-form reading.',
    version: '1.0.0',
  },
  tokens: {
    ...defaultTheme.tokens,
    colors: {
      ...defaultTheme.tokens.colors,
      background: '#fbf8f1',
      surface: '#fffdf8',
      surfaceAlt: '#eee7da',
      text: '#2e281f',
      textMuted: '#776b5a',
      primary: '#9b351f',
      primaryHover: '#702516',
      border: '#d9cfbf',
    },
    typography: {
      ...defaultTheme.tokens.typography,
      fontBody: 'Georgia, Cambria, Times New Roman, serif',
      fontHeading: 'Georgia, Cambria, Times New Roman, serif',
      fontSizeBase: '18px',
      lineHeightBody: '1.75',
      lineHeightHeading: '1.05',
    },
    layout: { ...defaultTheme.tokens.layout, contentWidth: '66ch' },
  },
  elements: {
    article: { backgroundColor: 'transparent', border: '0', padding: '0', boxShadow: 'none' },
    h1: { fontSize: 'clamp(2.8rem, 8vw, 5.8rem)', letterSpacing: '-0.045em' },
    h2: { fontSize: 'clamp(2rem, 5vw, 3.4rem)', letterSpacing: '-0.03em' },
    blockquote: {
      fontSize: '1.2em',
      fontStyle: 'italic',
      borderInlineStart: '0',
      borderBlock: '1px solid var(--color-border)',
      padding: 'var(--space-lg) 0',
    },
  },
  modes: {
    light: { colors: {} },
    dark: {
      colors: {
        background: '#181510',
        surface: '#201c16',
        surfaceAlt: '#2b251c',
        text: '#f2eadc',
        textMuted: '#b9ac99',
        primary: '#ff9576',
        primaryHover: '#ffb19b',
        border: '#453c31',
      },
    },
  },
})

export const documentationPreset = preset({
  metadata: {
    name: 'Documentation',
    description: 'Crisp sans-serif styling for technical documentation.',
    version: '1.0.0',
  },
  tokens: {
    ...defaultTheme.tokens,
    colors: {
      ...defaultTheme.tokens.colors,
      background: '#f8fafc',
      surface: '#ffffff',
      surfaceAlt: '#eef2f7',
      text: '#172033',
      textMuted: '#596579',
      primary: '#0a68d8',
      primaryHover: '#0753ad',
      border: '#d8e0eb',
      codeBackground: '#0d1726',
    },
    radius: { ...defaultTheme.tokens.radius, radiusMd: '0.35rem', radiusLg: '0.5rem' },
    layout: { ...defaultTheme.tokens.layout, contentWidth: '78ch' },
  },
  elements: {
    article: { backgroundColor: 'var(--color-surface)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-md)', padding: 'var(--space-xl)', boxShadow: 'none' },
    h1: { fontSize: '2.75rem', letterSpacing: '-0.035em' },
    h2: { fontSize: '1.8rem', borderBottom: '1px solid var(--color-border)', paddingBottom: '0.35em' },
  },
  modes: {
    light: { colors: {} },
    dark: {
      colors: {
        background: '#0f1724',
        surface: '#151f2e',
        surfaceAlt: '#1d2a3b',
        text: '#e8edf5',
        textMuted: '#a5b1c2',
        primary: '#78b7ff',
        primaryHover: '#a5ceff',
        border: '#2c3b50',
      },
    },
  },
})

export const academicPreset = preset({
  metadata: {
    name: 'Academic',
    description: 'Reserved typography and spacing for papers and scholarly notes.',
    version: '1.0.0',
  },
  tokens: {
    ...defaultTheme.tokens,
    colors: {
      ...defaultTheme.tokens.colors,
      background: '#fffefe',
      surface: '#ffffff',
      surfaceAlt: '#f4f4f4',
      text: '#111111',
      textMuted: '#555555',
      primary: '#174a7e',
      primaryHover: '#0f345a',
      border: '#cfcfcf',
    },
    typography: {
      ...defaultTheme.tokens.typography,
      fontBody: 'Charter, Georgia, Times New Roman, serif',
      fontHeading: 'Charter, Georgia, Times New Roman, serif',
      fontSizeBase: '17px',
      lineHeightBody: '1.7',
    },
    radius: { ...defaultTheme.tokens.radius, radiusSm: '0', radiusMd: '0', radiusLg: '0' },
    shadow: { shadowSm: 'none', shadowMd: 'none', shadowLg: 'none' },
    layout: { ...defaultTheme.tokens.layout, contentWidth: '70ch' },
  },
  elements: {
    article: { backgroundColor: 'transparent', border: '0', borderRadius: '0', padding: '0', boxShadow: 'none' },
    h1: { fontSize: '2.4rem', textAlign: 'center' },
    h2: { fontSize: '1.6rem' },
    blockquote: { borderInlineStart: '2px solid var(--color-border)', fontSize: '0.96em' },
  },
})

export const terminalPreset = preset({
  metadata: {
    name: 'Terminal',
    description: 'A monochrome, command-line inspired semantic theme.',
    version: '1.0.0',
  },
  tokens: {
    ...defaultTheme.tokens,
    colors: {
      ...defaultTheme.tokens.colors,
      background: '#071009',
      surface: '#0b160d',
      surfaceAlt: '#112017',
      text: '#b9f7c2',
      textMuted: '#75a97e',
      primary: '#74f38a',
      primaryHover: '#a6ffb5',
      primaryText: '#061008',
      secondary: '#66c877',
      border: '#244d2d',
      success: '#74f38a',
      warning: '#e0d06c',
      danger: '#ff817e',
      codeBackground: '#030804',
      codeText: '#c9ffd1',
    },
    typography: {
      ...defaultTheme.tokens.typography,
      fontBody: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
      fontHeading: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
      fontMono: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
      fontSizeBase: '15px',
      lineHeightBody: '1.55',
      fontWeightBold: '700',
    },
    radius: { ...defaultTheme.tokens.radius, radiusSm: '0', radiusMd: '0', radiusLg: '0' },
    shadow: { shadowSm: 'none', shadowMd: 'none', shadowLg: 'none' },
  },
  elements: {
    article: { backgroundColor: 'var(--color-surface)', border: '1px solid var(--color-border)', borderRadius: '0', padding: 'var(--space-lg)', boxShadow: 'none' },
    h1: { fontSize: '2.1rem', textTransform: 'uppercase', letterSpacing: '0.06em' },
    h2: { fontSize: '1.4rem', textTransform: 'uppercase', letterSpacing: '0.04em' },
    a: { color: 'var(--color-primary)', textDecoration: 'none' },
  },
  modes: {
    light: { colors: {} },
    dark: {
      colors: {
        background: '#071009',
        surface: '#0b160d',
        surfaceAlt: '#112017',
        text: '#b9f7c2',
        textMuted: '#75a97e',
        primary: '#74f38a',
        primaryHover: '#a6ffb5',
        primaryText: '#061008',
        border: '#244d2d',
      },
    },
  },
})


/**
 * Editable preset based on the upstream Simple.css stylesheet by Kev Quirk.
 * Source: https://github.com/kevquirk/simple.css
 * License: MIT — see THIRD_PARTY_NOTICES.md.
 *
 * The mapping intentionally expresses Simple.css through the Studio Theme model
 * so users can inspect and modify its semantic selectors visually.
 */
export const simpleCssPreset = preset({
  metadata: {
    name: 'Simple.css',
    description: 'An editable preset based on Kev Quirk’s Simple.css classless framework.',
    author: 'Kev Quirk / Simple.css contributors',
    version: '1.0.0',
  },
  tokens: {
    ...defaultTheme.tokens,
    colors: {
      ...defaultTheme.tokens.colors,
      background: '#ffffff',
      surface: '#f5f7ff',
      surfaceAlt: '#f5f7ff',
      text: '#212121',
      textMuted: '#585858',
      primary: '#0d47a1',
      primaryHover: '#1266e2',
      primaryText: '#ffffff',
      secondary: '#585858',
      border: '#898ea4',
      warning: '#ffdd33',
      danger: '#d81b60',
      codeBackground: '#f5f7ff',
      codeText: '#444444',
    },
    typography: {
      ...defaultTheme.tokens.typography,
      fontBody: '-apple-system, BlinkMacSystemFont, "Avenir Next", Avenir, "Nimbus Sans L", Roboto, "Noto Sans", "Segoe UI", Arial, Helvetica, "Helvetica Neue", sans-serif',
      fontHeading: '-apple-system, BlinkMacSystemFont, "Avenir Next", Avenir, "Nimbus Sans L", Roboto, "Noto Sans", "Segoe UI", Arial, Helvetica, "Helvetica Neue", sans-serif',
      fontMono: 'Consolas, Menlo, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
      fontSizeBase: '1.15rem',
      fontSizeXs: '0.9rem',
      fontSizeSm: '0.96rem',
      fontSizeMd: '1.15rem',
      fontSizeLg: '1.44rem',
      fontSizeXl: '3rem',
      lineHeightBody: '1.5',
      lineHeightHeading: '1.1',
      fontWeightNormal: '400',
      fontWeightMedium: '600',
      fontWeightBold: '700',
    },
    spacing: {
      spaceXs: '0.25rem',
      spaceSm: '0.5rem',
      spaceMd: '1rem',
      spaceLg: '1.5rem',
      spaceXl: '2rem',
      space2xl: '4rem',
    },
    radius: {
      radiusSm: '5px',
      radiusMd: '5px',
      radiusLg: '5px',
      radiusFull: '999px',
    },
    shadow: {
      shadowSm: 'none',
      shadowMd: 'none',
      shadowLg: 'none',
    },
    layout: {
      ...defaultTheme.tokens.layout,
      contentWidth: '45rem',
      wideWidth: '1200px',
      bodyPadding: '0.5rem',
      sectionSpacing: '3rem',
      headerWidth: '1200px',
      footerWidth: '45rem',
    },
  },
  elements: {
    html: {
      fontFamily: 'var(--font-body)',
      scrollBehavior: 'smooth',
      colorScheme: 'normal',
      background: 'initial',
    },
    body: {
      color: 'var(--color-text)',
      backgroundColor: 'var(--color-background)',
      fontFamily: 'var(--font-body)',
      fontSize: 'var(--font-size-base)',
      lineHeight: 'var(--line-height-body)',
      display: 'grid',
      gridTemplateColumns: '1fr min(45rem, 90%) 1fr',
      margin: '0',
    },
    'body > *': { gridColumn: '2' },
    header: {},
    'body > header': {
      backgroundColor: 'var(--color-surface)',
      borderBottom: '1px solid var(--color-border)',
      textAlign: 'center',
      padding: '0 0.5rem 2rem 0.5rem',
      gridColumn: '1 / -1',
    },
    'body > header > *:only-child': { marginBlockStart: '2rem' },
    'body > header h1': { maxWidth: '1200px', margin: '1rem auto' },
    'body > header p': { maxWidth: '40rem', margin: '1rem auto' },
    main: { paddingTop: '1.5rem' },
    footer: {},
    'body > footer': {
      marginTop: '4rem',
      padding: '2rem 1rem 1.5rem 1rem',
      color: 'var(--color-text-muted)',
      fontSize: '0.9rem',
      textAlign: 'center',
      borderTop: '1px solid var(--color-border)',
    },
    h1: { fontSize: '3rem', lineHeight: '1.1', overflowWrap: 'break-word' },
    h2: { fontSize: '2.6rem', marginTop: '3rem', lineHeight: '1.1', overflowWrap: 'break-word' },
    h3: { fontSize: '2rem', marginTop: '3rem', lineHeight: '1.1', overflowWrap: 'break-word' },
    h4: { fontSize: '1.44rem', overflowWrap: 'break-word' },
    h5: { fontSize: '1.15rem', overflowWrap: 'break-word' },
    h6: { fontSize: '0.96rem', overflowWrap: 'break-word' },
    p: { margin: '1.5rem 0', overflowWrap: 'break-word' },
    a: { color: 'var(--color-primary)' },
    nav: {},
    'header nav': { fontSize: '1rem', lineHeight: '2', padding: '1rem 0 0 0' },
    'header nav ul, header nav ol': {
      alignContent: 'space-around',
      alignItems: 'center',
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      listStyleType: 'none',
      margin: '0',
      padding: '0',
    },
    'header nav ul li, header nav ol li': { display: 'inline-block' },
    'header nav a, header nav a:visited': {
      margin: '0 0.5rem 1rem 0.5rem',
      border: '1px solid var(--color-border)',
      borderRadius: 'var(--radius-md)',
      color: 'var(--color-text)',
      display: 'inline-block',
      padding: '0.1rem 1rem',
      textDecoration: 'none',
    },
    aside: {
      backgroundColor: 'var(--color-surface)',
      border: '1px solid var(--color-border)',
      borderRadius: 'var(--radius-md)',
      marginBottom: '1rem',
      fontSize: '1rem',
      width: '30%',
      padding: '0 15px',
      marginInlineStart: '15px',
      float: 'right',
    },
    article: {
      border: '1px solid var(--color-border)',
      padding: '1rem',
      borderRadius: 'var(--radius-md)',
      marginBottom: '1rem',
      backgroundColor: 'transparent',
      boxShadow: 'none',
    },
    section: {
      borderTop: '1px solid var(--color-border)',
      borderBottom: '1px solid var(--color-border)',
      padding: '2rem 1rem',
      margin: '3rem 0',
    },
    details: {
      backgroundColor: 'var(--color-surface)',
      border: '1px solid var(--color-border)',
      borderRadius: 'var(--radius-md)',
      marginBottom: '1rem',
      padding: '0.7rem 1rem',
    },
    summary: {
      cursor: 'pointer',
      fontWeight: 'bold',
      padding: '0.7rem 1rem',
      margin: '-0.7rem -1rem',
      wordBreak: 'break-all',
    },
    table: { borderCollapse: 'collapse', margin: '1.5rem 0' },
    'td, th': { border: '1px solid var(--color-border)', textAlign: 'start', padding: '0.5rem' },
    th: { backgroundColor: 'var(--color-surface)', fontWeight: 'bold', textAlign: 'start', border: '1px solid var(--color-border)', padding: '0.5rem' },
    td: { border: '1px solid var(--color-border)', textAlign: 'start', padding: '0.5rem' },
    'tr:nth-child(even)': { backgroundColor: 'var(--color-surface)' },
    caption: { fontWeight: 'bold', marginBottom: '0.5rem', textAlign: 'start', color: 'var(--color-text)' },
    fieldset: { border: '1px solid var(--color-border)', padding: '1rem', borderRadius: 'var(--radius-md)', marginBottom: '1rem' },
    dialog: { backgroundColor: 'var(--color-background)', maxWidth: '40rem', margin: 'auto', border: '1px solid var(--color-border)', padding: '1rem', borderRadius: 'var(--radius-md)' },
    label: { display: 'block' },
    input: {
      color: 'var(--color-text)',
      backgroundColor: 'var(--color-background)',
      border: '1px solid var(--color-border)',
      borderRadius: 'var(--radius-md)',
      boxShadow: 'none',
      maxWidth: '100%',
      display: 'inline-block',
      fontSize: 'inherit',
      fontFamily: 'inherit',
      padding: '0.5em',
      marginBottom: '0.5rem',
    },
    textarea: {
      color: 'var(--color-text)',
      backgroundColor: 'var(--color-background)',
      border: '1px solid var(--color-border)',
      borderRadius: 'var(--radius-md)',
      boxShadow: 'none',
      maxWidth: '100%',
      width: '100%',
      display: 'inline-block',
      fontSize: 'inherit',
      fontFamily: 'inherit',
      padding: '0.5em',
      marginBottom: '0.5rem',
    },
    select: {
      color: 'var(--color-text)',
      backgroundColor: 'var(--color-background)',
      border: '1px solid var(--color-border)',
      borderRadius: 'var(--radius-md)',
      boxShadow: 'none',
      maxWidth: '100%',
      display: 'inline-block',
      fontSize: 'inherit',
      fontFamily: 'inherit',
      padding: '0.5em',
      marginBottom: '0.5rem',
    },
    button: {
      border: '1px solid var(--color-primary)',
      borderRadius: 'var(--radius-md)',
      backgroundColor: 'var(--color-primary)',
      color: 'var(--color-primary-text)',
      padding: '0.5rem 0.9rem',
      marginBottom: '0.5rem',
      textDecoration: 'none',
      lineHeight: 'normal',
      fontSize: 'inherit',
      fontFamily: 'inherit',
      boxShadow: 'none',
      maxWidth: '100%',
      display: 'inline-block',
      fontWeight: '400',
    },
    abbr: { cursor: 'help', textDecorationLine: 'underline', textDecorationStyle: 'dotted' },
    hr: { border: 'none', height: '1px', background: 'var(--color-border)', margin: '1rem auto' },
    mark: { padding: '2px 5px', borderRadius: 'var(--radius-md)', backgroundColor: 'var(--color-warning)', color: 'black' },
    img: { maxWidth: '100%', height: 'auto', borderRadius: 'var(--radius-md)' },
    video: { maxWidth: '100%', height: 'auto', borderRadius: 'var(--radius-md)' },
    figure: { margin: '0', display: 'block', overflowX: 'auto' },
    figcaption: { position: 'sticky', left: '0', textAlign: 'center', fontSize: '0.9rem', color: 'var(--color-text-muted)', marginBlock: '1rem' },
    blockquote: {
      marginInlineStart: '2rem',
      marginInlineEnd: '0',
      marginBlock: '2rem',
      padding: '0.4rem 0.8rem',
      borderInlineStart: '0.35rem solid var(--color-primary)',
      color: 'var(--color-text-muted)',
      fontStyle: 'italic',
    },
    cite: { fontSize: '0.9rem', color: 'var(--color-text-muted)', fontStyle: 'normal' },
    dt: { color: 'var(--color-text-muted)' },
    code: { fontFamily: 'var(--font-mono)', color: 'var(--color-danger)', backgroundColor: 'transparent', padding: '0' },
    kbd: { fontFamily: 'var(--font-mono)', color: 'var(--color-code-text)', border: '1px solid var(--color-code-text)', borderBottom: '3px solid var(--color-code-text)', borderRadius: 'var(--radius-md)', padding: '0.1rem 0.4rem' },
    samp: { fontFamily: 'var(--font-mono)', color: 'var(--color-danger)' },
    pre: {
      fontFamily: 'var(--font-mono)',
      backgroundColor: 'var(--color-surface)',
      border: '1px solid var(--color-border)',
      borderRadius: 'var(--radius-md)',
      marginBottom: '1rem',
      padding: '1rem 1.4rem',
      maxWidth: '100%',
      overflow: 'auto',
      color: 'var(--color-code-text)',
    },
    'pre code': { color: 'var(--color-code-text)', background: 'none', margin: '0', padding: '0' },
    progress: { width: '100%', backgroundColor: 'var(--color-surface)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-md)', marginBottom: '1rem' },
    sup: { verticalAlign: 'baseline', position: 'relative', top: '-0.4em' },
    sub: { verticalAlign: 'baseline', position: 'relative', top: '0.3em' },
  },
  states: {
    a: {
      hover: { textDecoration: 'none' },
      'focus-visible': { outline: '2px solid var(--color-primary)', outlineOffset: '1px' },
    },
    button: {
      hover: { backgroundColor: 'var(--color-primary-hover)', borderColor: 'var(--color-primary-hover)', cursor: 'pointer' },
      'focus-visible': { outline: '2px solid var(--color-primary)', outlineOffset: '1px' },
      disabled: { cursor: 'not-allowed', backgroundColor: 'var(--color-surface-alt)', borderColor: 'var(--color-surface-alt)', color: 'var(--color-text-muted)' },
    },
    input: {
      disabled: { cursor: 'not-allowed', backgroundColor: 'var(--color-surface-alt)', borderColor: 'var(--color-surface-alt)', color: 'var(--color-text-muted)' },
      checked: { backgroundColor: 'var(--color-primary)' },
    },
    textarea: {
      disabled: { cursor: 'not-allowed', backgroundColor: 'var(--color-surface-alt)', borderColor: 'var(--color-surface-alt)', color: 'var(--color-text-muted)' },
    },
    select: {
      disabled: { cursor: 'not-allowed', backgroundColor: 'var(--color-surface-alt)', borderColor: 'var(--color-surface-alt)', color: 'var(--color-text-muted)' },
    },
  },
  modes: {
    light: { colors: {} },
    dark: {
      colors: {
        background: '#212121',
        surface: '#2b2b2b',
        surfaceAlt: '#111111',
        text: '#dcdcdc',
        textMuted: '#ababab',
        primary: '#ffb300',
        primaryHover: '#ffe099',
        primaryText: '#212121',
        danger: '#f06292',
        codeBackground: '#2b2b2b',
        codeText: '#cccccc',
      },
    },
  },
  responsive: { mobile: 720, tablet: 720, desktop: 1440 },
})

export const presets = {
  Minimal: minimalPreset,
  Editorial: editorialPreset,
  Documentation: documentationPreset,
  Academic: academicPreset,
  Terminal: terminalPreset,
  'Simple.css': simpleCssPreset,
} as const

export type PresetName = keyof typeof presets
